WebApplicationnew -Finally/WebApplicationnew/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationnew.Data;
using WebApplicationnew.Models;

namespace WebApplicationnew.Controllers
{
    public class CategoriesController : Controller
    {
        private WebApplicationnewContext db = new WebApplicationnewContext();

    
        public ActionResult Index()
        {
           
            return View(db.Categories.OrderBy(c => c.Name).ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            foreach (var p in category.Products)
            {
                p.CategoryID = null;
            }
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationnew -Finally/WebApplicationnew/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages.Html;
using WebApplicationnew.Data;
using WebApplicationnew.Models;
using WebApplicationnew.ViewModel;
using static WebApplicationnew.ViewModel.ProductIndexViewModel;
using PagedList;
using System.Net.NetworkInformation;
using System.Security.Policy;

namespace WebApplicationnew.Controllers
{
    public class ProductsController : Controller
    {
        private WebApplicationnewContext db = new WebApplicationnewContext();

        // GET: Products
        public ActionResult Index(string category, string search, int? page, String sortBy)
        {

            //instantiate a new view model
            ProductIndexViewModel viewModel = new ProductIndexViewModel();
            var products = db.Products.Include(p => p.Category);
            //perform the search and save the search string to the viewModel
            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.Name.Contains(search) ||
                p.Description.Contains(search) ||
               p.Category.Name.Contains(search));
                viewModel.Search = search;
            }

 viewModel.CatsWithCount = from matchingProducts in products
                           where matchingProducts.CategoryID != null
                           group matchingProducts by
                           matchingProducts.Category.Name into
                            catGroup
                           select new CategoryWithCount()
                           {
                               CategoryName = catGroup.Key,
                               ProductCount = catGroup.Count()
                           };
            if (!String.IsNullOrEmpty(category))
            {
                products = products.Where(p => p.Category.Name == category);
                viewModel.Category = category;
            }
            //sort the results
            switch (sortBy)
            {
                case "price_lowest":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "price_highest":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    products = products.OrderBy(p => p.Name);
                    break;
            }
            //viewModel.Products = products; 
            viewModel.SortBy = sortBy;
            viewModel.Sorts = new Dictionary<string, string>
 {
 {"Price low to high", "price_lowest" },
 {"Price high to low", "price_highest" }
 };
            const int PageItems = 4;
            int currentPage = (page ?? 1);
            viewModel.Products = products.ToPagedList(currentPage, PageItems);
            return View(viewModel);
        }

    






    // GET: Products/Details/5
    public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price,Description,CategoryID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name",  product.CategoryID);
            return View(product);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price,Description,CategoryID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationnew -Finally/WebApplicationnew/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
    <html lang="en">
    
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        @*<meta charset="utf-8" />*@
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="my-element my-container" style="background-color: #668B78">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark justify-content-center" style="background-color: #214129">
                <div class="container d-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item d-inline">
                            <a href="#" class="nav-link embroidery-culture">Embroidery Culture</a>
                        </li>
                        <li class="nav-item d-inline">
                            <a href="#" class="nav-link separator"> | </a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("History", "History", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Masterwork", "Masterwork", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Category", "Index", "Categories", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Merchandises", "Index", "Products", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Contact us", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    </ul>



                    @using (Html.BeginForm("Index", "Products", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
                    {
                        <div class="form-group search-form">
                            @Html.TextBox("Search", null, new
                       {
                           @class = "form-control",
                           @placeholder = "Search Merchandises"
                       })
                        </div>
                        <button type="submit" class="btn btn-default submit-button">Submit</button>
                    }

                </div>


            </nav>


            <div class="line">
                <hr class="my-0" style="background-color: #ccc;">
            </div>

            <div class="picture">
                <img src="~/picture/Embroidery.jpg" alt="Embroidery" class="img-fluid">
            </div>

            <div class="container body-content">
                @RenderBody()
                <hr class="hr">
                <footer>
                    <div id="TwoContact">
                        <div class="contact">
                            <img class="image" src="~/picture/yejiao.png" alt="">
                            <div class="email">
                                @Html.ActionLink("Email: 1293871845@qq.com", "Contact", "Home")
                            </div>
                        </div>



                        <div class="contact">
                            <img class="image" src="~/picture/下.png" alt="">
                            <div class="email">
                                <a href="#" onclick="validateHTML()">Validate HTML5</a>
                                <a href="#" onclick="validateCSS()">Validate CSS3</a>
                            </div>
                        </div>


                    </div>

                </footer>
            </div>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>